import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import Header from "@/components/Header";
import Hero from "@/components/homepage/hero/Hero";
import About from "@/components/homepage/About";
import WorkExperience from "@/components/homepage/WorkExperience";
import Skills from "@/components/homepage/Skills";
import Link from "next/link";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-[color:var(--primary-color)] text-white h-screen snap-y snap-mandatory overflow-x-hidden z-0">
        {/* Header */}
        <Header />

        {/* Hero */}
        <section id="hero" className="snap-start">
          <Hero />
        </section>

        {/* About */}
        <section id="about" className="snap-center">
          <About />
        </section>

        {/* Work experience */}
        <section id="workexperience" className="snap-center">
          <WorkExperience />
        </section>

        {/* Skills */}
        <section id="skills" className="snap-start">
          <Skills />
        </section>
      </div>
    </>
  );
};

export default Home;
